//! Daemon auto-spawn (plan §1.1 rule 3, M2/B6): when ui-rpc discovery fails,
//! locate a backend, spawn it detached under the current `ORCHESTRA_HOME`,
//! and wait for the `ui-sock` pointer to appear.
//!
//! Location order (the plan's, most-explicit first):
//!   1. `$ORCHESTRA_DAEMON_CMD` — a full command line, run through `sh -c`
//!      (E2E suites point this at `node dist-electron/daemon.js`);
//!   2. the `~/.local/bin/orchestra` CLI shim (written by cli-shim.ts) — its
//!      `exec "<AppImage>" cli "$@"` line names the installed AppImage, which
//!      we invoke as `<AppImage> daemon`;
//!   3. dev checkout: `dist-electron/daemon.js` found by walking up from the
//!      running executable (native/target/…) or the cwd, run under `node`.
//!
//! Failure diagnosis is part of the contract (plan §1.1): a daemon that lost
//! the backend lock names the holder, and the caller turns that into the
//! right story — "Orchestra (Electron) owns this home, attach to it" vs
//! genuine stale-lock guidance.
//!
//! Pure std module (no GTK): everything here unit-tests headlessly.

use std::io::Read;
use std::os::unix::process::CommandExt;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::time::{Duration, Instant};

use crate::backend::discover_socket;

/// Marker cli-shim.ts writes into shims it owns; we refuse to parse a
/// user-installed `orchestra` binary or foreign script.
const SHIM_MARKER: &str = "auto-generated by Orchestra";

/// How the daemon will be started.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DaemonCommand {
    /// `$ORCHESTRA_DAEMON_CMD`, run via `sh -c` so it may carry arguments.
    Shell(String),
    /// `<AppImage> daemon` — canonical for installed users (plan §1.2).
    AppImage(PathBuf),
    /// `node <repo>/dist-electron/daemon.js` — dev checkouts.
    NodeScript(PathBuf),
}

impl DaemonCommand {
    /// Human-readable form for banners/logs.
    pub fn describe(&self) -> String {
        match self {
            DaemonCommand::Shell(cmd) => cmd.clone(),
            DaemonCommand::AppImage(p) => format!("{} daemon", p.display()),
            DaemonCommand::NodeScript(p) => format!("node {}", p.display()),
        }
    }
}

/// Resolve the daemon command per the plan's order. `user_home` is the USER's
/// home (shim location), not the orchestra home.
pub fn locate_daemon_command(user_home: &Path) -> Option<DaemonCommand> {
    if let Some(cmd) = std::env::var_os("ORCHESTRA_DAEMON_CMD") {
        let cmd = cmd.to_string_lossy().trim().to_string();
        if !cmd.is_empty() {
            return Some(DaemonCommand::Shell(cmd));
        }
    }
    if let Some(appimage) = appimage_from_shim(&user_home.join(".local/bin/orchestra")) {
        return Some(DaemonCommand::AppImage(appimage));
    }
    let mut starts = vec![std::env::current_dir().ok()];
    starts.insert(
        0,
        std::env::current_exe()
            .ok()
            .and_then(|p| p.parent().map(Path::to_path_buf)),
    );
    for start in starts.into_iter().flatten() {
        if let Some(script) = daemon_script_above(&start) {
            return Some(DaemonCommand::NodeScript(script));
        }
    }
    None
}

/// Parse the AppImage path out of the CLI shim's `exec "<path>" cli "$@"`
/// line. Only shims carrying the cli-shim.ts marker are trusted, and the
/// target must still exist (the shim self-heals on next Electron launch, but
/// a deleted AppImage would otherwise fail with a confusing ENOENT).
pub fn appimage_from_shim(shim: &Path) -> Option<PathBuf> {
    let body = std::fs::read_to_string(shim).ok()?;
    if !body.contains(SHIM_MARKER) {
        return None;
    }
    let exec_line = body
        .lines()
        .find(|l| l.trim_start().starts_with("exec \""))?;
    let rest = exec_line.split('"').nth(1)?; // exec "<path>" … → <path>
    let p = PathBuf::from(rest);
    p.is_file().then_some(p)
}

/// Walk up from `start` looking for an orchestra repo checkout with a built
/// daemon bundle (`dist-electron/daemon.js` next to the orchestra
/// package.json).
fn daemon_script_above(start: &Path) -> Option<PathBuf> {
    let mut dir = Some(start);
    for _ in 0..8 {
        let d = dir?;
        let script = d.join("dist-electron/daemon.js");
        if script.is_file() && is_orchestra_package(&d.join("package.json")) {
            return Some(script);
        }
        dir = d.parent();
    }
    None
}

fn is_orchestra_package(pkg: &Path) -> bool {
    std::fs::read_to_string(pkg)
        .ok()
        .and_then(|raw| serde_json::from_str::<serde_json::Value>(&raw).ok())
        .is_some_and(|v| v["name"] == "orchestra")
}

/// A daemon we spawned. The child handle stays reapable (`try_wait`) during
/// the socket wait; afterwards hand it to [`reap_in_background`].
#[derive(Debug)]
pub struct SpawnedDaemon {
    pub pid: u32,
    /// Where the daemon's early stdout+stderr go — the file to quote when the
    /// spawn fails before the daemon's own logger takes over.
    pub spawn_log: PathBuf,
    child: Child,
}

/// Spawn the daemon detached (own process group — it must survive this app,
/// plan §1.1 rule 3) with `ORCHESTRA_HOME` pinned to `orchestra_home`. Early
/// output is captured to `<home>/logs/daemon-spawn.log` so a pre-logger crash
/// (e.g. the backend-lock refusal) stays diagnosable.
pub fn spawn_daemon(cmd: &DaemonCommand, orchestra_home: &Path) -> std::io::Result<SpawnedDaemon> {
    let logs_dir = orchestra_home.join("logs");
    std::fs::create_dir_all(&logs_dir)?;
    let spawn_log = logs_dir.join("daemon-spawn.log");
    let out = std::fs::File::create(&spawn_log)?;
    let err = out.try_clone()?;

    let mut command = match cmd {
        DaemonCommand::Shell(line) => {
            let mut c = Command::new("sh");
            c.arg("-c").arg(line);
            c
        }
        DaemonCommand::AppImage(p) => {
            let mut c = Command::new(p);
            c.arg("daemon");
            c
        }
        DaemonCommand::NodeScript(script) => {
            let mut c = Command::new("node");
            c.arg(script);
            c
        }
    };
    let child = command
        .env("ORCHESTRA_HOME", orchestra_home)
        .stdin(Stdio::null())
        .stdout(out)
        .stderr(err)
        .process_group(0)
        .spawn()?;
    Ok(SpawnedDaemon {
        pid: child.id(),
        spawn_log,
        child,
    })
}

/// Outcome of waiting for the daemon's ui-sock.
#[derive(Debug)]
pub enum WaitOutcome {
    /// Socket is up — attach to it.
    Ready(PathBuf),
    /// The daemon exited before serving; `output_tail` is the end of its
    /// spawn log (where the backend-lock refusal lands).
    Exited {
        code: Option<i32>,
        output_tail: String,
    },
    /// Still no socket after the timeout (daemon may be wedged mid-boot).
    TimedOut,
}

/// Poll for the ui-sock while watching the child. 250 ms cadence; a fresh
/// daemon on a dev box serves within ~1–3 s, AppImage cold starts a bit more —
/// callers pass ~15 s.
pub fn wait_for_socket(
    daemon: &mut SpawnedDaemon,
    orchestra_home: &Path,
    timeout: Duration,
) -> WaitOutcome {
    let deadline = Instant::now() + timeout;
    loop {
        if let Some(sock) = discover_socket(orchestra_home) {
            return WaitOutcome::Ready(sock);
        }
        match daemon.child.try_wait() {
            Ok(Some(status)) => {
                // Give the pointer one last look — a daemon that serves and
                // exits immediately is not a thing, but losing a race to a
                // slower filesystem is.
                if let Some(sock) = discover_socket(orchestra_home) {
                    return WaitOutcome::Ready(sock);
                }
                return WaitOutcome::Exited {
                    code: status.code(),
                    output_tail: tail_of(&daemon.spawn_log, 2000),
                };
            }
            Ok(None) => {}
            Err(_) => {}
        }
        if Instant::now() >= deadline {
            return WaitOutcome::TimedOut;
        }
        std::thread::sleep(Duration::from_millis(250));
    }
}

/// Reap the child's eventual exit from a background thread so a daemon that
/// dies later never lingers as a zombie of the GTK process.
pub fn reap_in_background(daemon: SpawnedDaemon) {
    let mut child = daemon.child;
    std::thread::Builder::new()
        .name("daemon-reaper".into())
        .spawn(move || {
            let _ = child.wait();
        })
        .ok();
}

/// Best-effort SIGTERM for `--stop-daemon-on-exit`. Only ever called with the
/// pid WE spawned this session — never a discovered backend's.
pub fn stop_daemon(pid: u32) {
    let _ = Command::new("kill")
        .args(["-TERM", &pid.to_string()])
        .status();
}

fn tail_of(path: &Path, max: usize) -> String {
    let mut s = String::new();
    if let Ok(mut f) = std::fs::File::open(path) {
        let _ = f.read_to_string(&mut s);
    }
    if s.len() > max {
        let cut = s.len() - max;
        // Don't split a UTF-8 char.
        let cut = (cut..s.len())
            .find(|i| s.is_char_boundary(*i))
            .unwrap_or(cut);
        s = format!("…{}", &s[cut..]);
    }
    s.trim_end().to_string()
}

// ---- exit diagnosis --------------------------------------------------------

/// Mirror of backend-lock.ts's on-disk shape (`<home>/backend.lock`).
#[derive(Debug, Clone, PartialEq, Eq, serde::Deserialize)]
pub struct BackendLockInfo {
    pub pid: u32,
    pub kind: String, // 'electron' | 'daemon'
}

pub fn read_backend_lock(orchestra_home: &Path) -> Option<BackendLockInfo> {
    let raw = std::fs::read_to_string(orchestra_home.join("backend.lock")).ok()?;
    serde_json::from_str(&raw).ok()
}

/// Why the spawned daemon refused to start.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ExitDiagnosis {
    /// Lost the backend lock (plan §1.1 rule 1). The holder decides the
    /// story: an Electron holder should be serving ui-rpc itself.
    LockHeld { kind: String, pid: Option<u32> },
    /// Anything else — surface the output tail.
    Other,
}

/// Classify a daemon exit from its output + the lock file. The daemon's
/// refusal line is "an orchestra <kind> backend (pid N) already owns <home>…"
/// (daemon.ts); the lock file is the structured source for holder details.
pub fn diagnose_exit(output_tail: &str, orchestra_home: &Path) -> ExitDiagnosis {
    if !output_tail.contains("already owns") {
        return ExitDiagnosis::Other;
    }
    match read_backend_lock(orchestra_home) {
        Some(lock) => ExitDiagnosis::LockHeld {
            kind: lock.kind,
            pid: Some(lock.pid),
        },
        // Refused on the lock but the file vanished since — still a
        // contention story, holder unknown.
        None => ExitDiagnosis::LockHeld {
            kind: "unknown".into(),
            pid: None,
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_dir(test: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("orch-gtk-daemon-{}-{test}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn shim_parse_extracts_the_appimage() {
        let dir = temp_dir("shim");
        let appimage = dir.join("Orchestra.AppImage");
        std::fs::write(&appimage, "").unwrap();
        let shim = dir.join("orchestra");
        std::fs::write(
            &shim,
            format!(
                "#!/bin/sh\n# {SHIM_MARKER}. Safe to delete.\nexec \"{}\" cli \"$@\"\n",
                appimage.display()
            ),
        )
        .unwrap();
        assert_eq!(appimage_from_shim(&shim), Some(appimage));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn shim_without_marker_is_untrusted() {
        let dir = temp_dir("foreign");
        let shim = dir.join("orchestra");
        std::fs::write(&shim, "#!/bin/sh\nexec \"/usr/bin/something\" cli \"$@\"\n").unwrap();
        assert_eq!(appimage_from_shim(&shim), None);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn shim_with_missing_target_is_skipped() {
        let dir = temp_dir("gone");
        let shim = dir.join("orchestra");
        std::fs::write(
            &shim,
            format!(
                "#!/bin/sh\n# {SHIM_MARKER}\nexec \"{}/nope.AppImage\" cli \"$@\"\n",
                dir.display()
            ),
        )
        .unwrap();
        assert_eq!(appimage_from_shim(&shim), None);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn spawn_wait_reports_a_fast_exit_with_output() {
        let dir = temp_dir("exit");
        let mut spawned = spawn_daemon(
            &DaemonCommand::Shell("echo 'boom from the fake daemon' >&2; exit 3".into()),
            &dir,
        )
        .unwrap();
        match wait_for_socket(&mut spawned, &dir, Duration::from_secs(5)) {
            WaitOutcome::Exited { code, output_tail } => {
                assert_eq!(code, Some(3));
                assert!(output_tail.contains("boom from the fake daemon"));
            }
            other => panic!("expected Exited, got {other:?}"),
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn spawn_wait_attaches_when_the_socket_appears() {
        let dir = temp_dir("ready");
        let sock = dir.join("fake.sock");
        // Fake daemon: write the pointer file after a beat, then linger.
        let cmd = DaemonCommand::Shell(format!(
            "sleep 0.3; touch '{sock}'; printf '%s' '{sock}' > '{ptr}'; sleep 30",
            sock = sock.display(),
            ptr = dir.join("ui-sock").display(),
        ));
        let mut spawned = spawn_daemon(&cmd, &dir).unwrap();
        match wait_for_socket(&mut spawned, &dir, Duration::from_secs(10)) {
            WaitOutcome::Ready(found) => assert_eq!(found, sock),
            other => panic!("expected Ready, got {other:?}"),
        }
        stop_daemon(spawned.pid);
        reap_in_background(spawned);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn lock_contention_is_diagnosed_from_output_and_lockfile() {
        let dir = temp_dir("lock");
        std::fs::write(
            dir.join("backend.lock"),
            r#"{"pid": 4242, "kind": "electron", "startedAt": 1}"#,
        )
        .unwrap();
        let tail = format!(
            "an orchestra electron backend (pid 4242) already owns {} — refusing to start a second backend",
            dir.display()
        );
        assert_eq!(
            diagnose_exit(&tail, &dir),
            ExitDiagnosis::LockHeld {
                kind: "electron".into(),
                pid: Some(4242)
            }
        );
        assert_eq!(diagnose_exit("segfault", &dir), ExitDiagnosis::Other);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn env_override_wins_location_order() {
        // Env-var tests can't run in parallel with each other safely; this is
        // the only test touching ORCHESTRA_DAEMON_CMD.
        std::env::set_var("ORCHESTRA_DAEMON_CMD", "node /tmp/custom-daemon.js");
        let got = locate_daemon_command(Path::new("/nonexistent-home"));
        std::env::remove_var("ORCHESTRA_DAEMON_CMD");
        assert_eq!(
            got,
            Some(DaemonCommand::Shell("node /tmp/custom-daemon.js".into()))
        );
    }
}
