import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { orchestraHome } from './platform';
import { log } from './logger';

// The shipped `orchestra` CLI lives inside the app bundle (dist-electron/cli.js,
// reached via `<app> cli …`). A package.json `bin` entry only helps npm
// installs, so a downloaded AppImage / installed .exe leaves no `orchestra` on
// PATH. To make the CLI discoverable we drop a tiny shim on GUI startup that
// re-invokes this exact executable in cli mode. The shim is idempotent and
// self-updating: if the binary moved/renamed, the next launch rewrites it.
//
// Per platform:
//   - Linux AppImage:  ~/.local/bin/orchestra  -> `"$APPIMAGE" cli "$@"`  (sh)
//   - Windows:         %LOCALAPPDATA%\Orchestra\bin\orchestra.cmd -> `"<exe>" cli %*`
//   - macOS / other:   skipped for now (no agreed install location; the CLI is
//                       still reachable via `<App>.app/Contents/MacOS/Orchestra cli`).
//
// Always best-effort: a failure here must never affect GUI startup.

const SHIM_MARKER = 'auto-generated by Orchestra';

interface ShimPlan {
  dir: string;
  file: string;
  body: string;
}

/** Decide what shim (if any) to install for the current platform + packaging. */
function planShim(): ShimPlan | null {
  if (process.platform === 'win32') {
    // Installed Electron app — point the shim at our own executable. `%*`
    // forwards all args; the marker line lets us recognize our own shim.
    const exe = process.execPath;
    const dir = path.join(
      process.env.LOCALAPPDATA || path.join(os.homedir(), 'AppData', 'Local'),
      'Orchestra',
      'bin',
    );
    const body = [
      '@echo off',
      `rem ${SHIM_MARKER}. Safe to delete.`,
      `"${exe}" cli %*`,
      '',
    ].join('\r\n');
    return { dir, file: path.join(dir, 'orchestra.cmd'), body };
  }

  if (process.platform === 'linux') {
    // Only the AppImage gives a stable single-file path to re-invoke. A distro
    // package / `npm run dev` has no such target, so skip (run cli.js directly).
    const appImage = process.env.APPIMAGE;
    if (!appImage) return null;
    const dir = path.join(os.homedir(), '.local', 'bin');
    // exec replaces the shell so the CLI's exit code propagates unchanged.
    const body = ['#!/bin/sh', `# ${SHIM_MARKER}. Safe to delete.`, `exec "${appImage}" cli "$@"`, ''].join(
      '\n',
    );
    return { dir, file: path.join(dir, 'orchestra'), body };
  }

  // macOS and anything else: no install location wired up yet.
  return null;
}

/**
 * Best-effort install/refresh of the `orchestra` CLI shim so the CLI is
 * reachable as a plain `orchestra` command. No-ops where there's no stable
 * target or agreed location, and never throws.
 */
export function installCliShim(): void {
  try {
    const plan = planShim();
    if (!plan) return;

    // Don't clobber a pre-existing `orchestra` that isn't ours (e.g. a real
    // binary the user installed). Only manage files we created.
    if (fs.existsSync(plan.file)) {
      const existing = fs.readFileSync(plan.file, 'utf8');
      if (!existing.includes(SHIM_MARKER)) {
        log.warn(`${plan.file} exists and is not ours — leaving it untouched`);
        return;
      }
      if (existing === plan.body) return; // already ours and current
    }

    fs.mkdirSync(plan.dir, { recursive: true });
    // 0o755 is meaningless on Windows (ignored) but correct for the POSIX sh shim.
    fs.writeFileSync(plan.file, plan.body, { mode: 0o755 });
    log.info(`installed orchestra CLI shim at ${plan.file}`);

    // The shim only resolves if its dir is on PATH. On Linux ~/.local/bin is on
    // PATH by default on most distros; on Windows %LOCALAPPDATA%\Orchestra\bin
    // is NOT, so the NSIS installer should add it (or the user does). Flag it
    // either way so a missing `orchestra` command isn't a mystery.
    const pathEntries = (process.env.PATH ?? '').split(path.delimiter);
    if (!pathEntries.includes(plan.dir)) {
      log.warn(`${plan.dir} is not on PATH — add it so the 'orchestra' command resolves`);
    }
  } catch (e) {
    log.warn('failed to install orchestra CLI shim', e);
  }
}

// ---------- Agent-facing shim ----------
//
// installCliShim() above is for a HUMAN typing `orchestra` in their own
// terminal: it lands in a conventional user bin dir that may or may not be on
// PATH (and is skipped entirely on macOS). That's too unreliable for the agent
// PTYs, where the injected skills/hooks now invoke `orchestra <subcommand>`
// directly and the GUI's inherited login PATH can't be trusted to contain any
// shim dir. So we ALSO drop a shim into a dir orchestra fully controls and then
// prepend that dir to every agent PTY's PATH (see main/pty.ts) — guaranteeing a
// bare `orchestra` resolves in the agent shell on every platform.

/**
 * The orchestra-owned bin dir that main/pty.ts prepends to each agent PTY's
 * PATH. Kept separate from the user-facing shim location so we never depend on
 * the user's login PATH for agent-driven CLI calls. Under the Orchestra home
 * root (honoring $ORCHESTRA_HOME) so an isolated instance — a dev build, a
 * smoke-tested daemon — writes ITS OWN shim instead of clobbering the packaged
 * app's target for every live agent; the packaged default is the same
 * ~/.orchestra/bin as always.
 */
export function agentCliBinDir(): string {
  return path.join(orchestraHome(), 'bin');
}

/**
 * Best-effort install/refresh of the agent-facing `orchestra` shim in
 * agentCliBinDir(). Unlike installCliShim() this covers every platform
 * (including macOS) because we force its dir onto the PTY PATH rather than
 * hoping the user already has one. Rewritten on each GUI startup so the
 * re-invocation target stays fresh (an AppImage's mount path changes per run).
 * Never throws.
 */
export function installAgentCliShim(): void {
  try {
    const dir = agentCliBinDir();
    fs.mkdirSync(dir, { recursive: true });
    // Prefer the stable AppImage path when present; otherwise re-invoke this
    // exact executable. Both dispatch to CLI mode via the `cli` arg handled at
    // the top of main/index.ts, so no second GUI window is ever opened. A
    // plain-Node host (the daemon under `node daemon.js`) has no cli-mode
    // dispatch in its own entry, so its shim runs the bundled cli.js sitting
    // next to the entry bundle directly.
    const target = process.env.APPIMAGE || process.execPath;
    const invoke = process.versions.electron
      ? `"${target}" cli`
      : `"${process.execPath}" "${path.join(__dirname, 'cli.js')}"`;
    if (process.platform === 'win32') {
      const body = ['@echo off', `rem ${SHIM_MARKER}. Safe to delete.`, `${invoke} %*`, ''].join(
        '\r\n',
      );
      fs.writeFileSync(path.join(dir, 'orchestra.cmd'), body);
    } else {
      // exec replaces the shell so the CLI's exit code propagates unchanged.
      const body = ['#!/bin/sh', `# ${SHIM_MARKER}. Safe to delete.`, `exec ${invoke} "$@"`, ''].join(
        '\n',
      );
      fs.writeFileSync(path.join(dir, 'orchestra'), body, { mode: 0o755 });
    }
  } catch (e) {
    log.warn('failed to install agent orchestra CLI shim', e);
  }
}

// ---------- Login-browser shim ----------
//
// The interactive `claude /login` auto-opens the OAuth URL via the `open`
// package, which on Linux execs `xdg-open` (and on macOS `open`) from PATH.
// Left alone, that lands in the system browser — whose claude.ai session is
// the user's MAIN account, so a secondary account's login silently authorizes
// the wrong account. The login PTY (and only it) gets this shim dir prepended
// to PATH: fake `xdg-open`/`open` scripts forward the URL to the running app
// (`orchestra login-url` → the /loginUrl socket route), which opens it in the
// account's isolated browser window instead (see main/login-browser.ts).

/**
 * Best-effort install of the `xdg-open`/`open` interceptors, returning the
 * shim dir to prepend to the login PTY's PATH — or null on Windows (the `open`
 * package launches the browser through powershell there, which we don't shim;
 * the login modal's link routing still covers the printed fallback URL) or on
 * any write failure (login then degrades to the old system-browser behaviour).
 */
export function installLoginBrowserShim(): string | null {
  if (process.platform === 'win32') return null;
  try {
    const dir = path.join(agentCliBinDir(), 'login-shim');
    fs.mkdirSync(dir, { recursive: true });
    // Absolute path to the agent shim so this works even if claude launches
    // the opener with a sanitized PATH. Forward only the first web URL among
    // the args (`open` may pass flags like -a first); swallow anything else so
    // a stray non-URL open can't error the login TUI.
    const orchestra = path.join(agentCliBinDir(), 'orchestra');
    const body = [
      '#!/bin/sh',
      `# ${SHIM_MARKER}. Safe to delete.`,
      '# Routes an account-login browser-open into the Orchestra app so the',
      '# OAuth page opens in that account\'s isolated login window.',
      'for a in "$@"; do',
      '  case "$a" in',
      `    http://*|https://*) exec "${orchestra}" login-url "$a" ;;`,
      '  esac',
      'done',
      'exit 0',
      '',
    ].join('\n');
    for (const name of ['xdg-open', 'open']) {
      fs.writeFileSync(path.join(dir, name), body, { mode: 0o755 });
    }
    return dir;
  } catch (e) {
    log.warn('failed to install login-browser shim', e);
    return null;
  }
}
