import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { log } from './logger';

// The shipped `orchestra` CLI lives inside the app bundle (dist-electron/cli.js,
// reached via `<app> cli …`). A package.json `bin` entry only helps npm
// installs, so a downloaded AppImage / installed .exe leaves no `orchestra` on
// PATH. To make the CLI discoverable we drop a tiny shim on GUI startup that
// re-invokes this exact executable in cli mode. The shim is idempotent and
// self-updating: if the binary moved/renamed, the next launch rewrites it.
//
// Per platform:
//   - Linux AppImage:  ~/.local/bin/orchestra  -> `"$APPIMAGE" cli "$@"`  (sh)
//   - Windows:         %LOCALAPPDATA%\Orchestra\bin\orchestra.cmd -> `"<exe>" cli %*`
//   - macOS / other:   skipped for now (no agreed install location; the CLI is
//                       still reachable via `<App>.app/Contents/MacOS/Orchestra cli`).
//
// Always best-effort: a failure here must never affect GUI startup.

const SHIM_MARKER = 'auto-generated by Orchestra';

interface ShimPlan {
  dir: string;
  file: string;
  body: string;
}

/** Decide what shim (if any) to install for the current platform + packaging. */
function planShim(): ShimPlan | null {
  if (process.platform === 'win32') {
    // Installed Electron app — point the shim at our own executable. `%*`
    // forwards all args; the marker line lets us recognize our own shim.
    const exe = process.execPath;
    const dir = path.join(
      process.env.LOCALAPPDATA || path.join(os.homedir(), 'AppData', 'Local'),
      'Orchestra',
      'bin',
    );
    const body = [
      '@echo off',
      `rem ${SHIM_MARKER}. Safe to delete.`,
      `"${exe}" cli %*`,
      '',
    ].join('\r\n');
    return { dir, file: path.join(dir, 'orchestra.cmd'), body };
  }

  if (process.platform === 'linux') {
    // Only the AppImage gives a stable single-file path to re-invoke. A distro
    // package / `npm run dev` has no such target, so skip (run cli.js directly).
    const appImage = process.env.APPIMAGE;
    if (!appImage) return null;
    const dir = path.join(os.homedir(), '.local', 'bin');
    // exec replaces the shell so the CLI's exit code propagates unchanged.
    const body = ['#!/bin/sh', `# ${SHIM_MARKER}. Safe to delete.`, `exec "${appImage}" cli "$@"`, ''].join(
      '\n',
    );
    return { dir, file: path.join(dir, 'orchestra'), body };
  }

  // macOS and anything else: no install location wired up yet.
  return null;
}

/**
 * Best-effort install/refresh of the `orchestra` CLI shim so the CLI is
 * reachable as a plain `orchestra` command. No-ops where there's no stable
 * target or agreed location, and never throws.
 */
export function installCliShim(): void {
  try {
    const plan = planShim();
    if (!plan) return;

    // Don't clobber a pre-existing `orchestra` that isn't ours (e.g. a real
    // binary the user installed). Only manage files we created.
    if (fs.existsSync(plan.file)) {
      const existing = fs.readFileSync(plan.file, 'utf8');
      if (!existing.includes(SHIM_MARKER)) {
        log.warn(`${plan.file} exists and is not ours — leaving it untouched`);
        return;
      }
      if (existing === plan.body) return; // already ours and current
    }

    fs.mkdirSync(plan.dir, { recursive: true });
    // 0o755 is meaningless on Windows (ignored) but correct for the POSIX sh shim.
    fs.writeFileSync(plan.file, plan.body, { mode: 0o755 });
    log.info(`installed orchestra CLI shim at ${plan.file}`);

    // The shim only resolves if its dir is on PATH. On Linux ~/.local/bin is on
    // PATH by default on most distros; on Windows %LOCALAPPDATA%\Orchestra\bin
    // is NOT, so the NSIS installer should add it (or the user does). Flag it
    // either way so a missing `orchestra` command isn't a mystery.
    const pathEntries = (process.env.PATH ?? '').split(path.delimiter);
    if (!pathEntries.includes(plan.dir)) {
      log.warn(`${plan.dir} is not on PATH — add it so the 'orchestra' command resolves`);
    }
  } catch (e) {
    log.warn('failed to install orchestra CLI shim', e);
  }
}
