//! Build script for orchestra-gtk. Three jobs:
//!  1. Version lockstep (plan §9): read the REPO version from package.json and
//!     expose it as ORCHESTRA_APP_VERSION — one bump versions both artifacts.
//!     Code uses `crate::app_version()`, never CARGO_PKG_VERSION (the crate's
//!     own 0.1.x, deliberately not the product version).
//!  2. Render the chime recipes (native/chime-gen — the port of
//!     src/renderer/chime.ts) into OUT_DIR; sound.rs embeds the bytes via the
//!     generated chime_assets.rs, so the binary is self-contained and the
//!     shipped audio can never drift from the recipe tables (chime-gen's tests
//!     pin those against chime.ts).
//!  3. Link `libfontconfig` for the app-font registration in `terminal::fonts`
//!     (fontconfig is present transitively via pango but not on the link line,
//!     so its `FcConfig*` symbols are otherwise undefined).

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    // ---- 1. version lockstep: package.json → ORCHESTRA_APP_VERSION ----
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR");
    let pkg = Path::new(&manifest).join("../../package.json");
    println!("cargo:rerun-if-changed={}", pkg.display());
    let raw = std::fs::read_to_string(&pkg)
        .unwrap_or_else(|e| panic!("cannot read {} for version lockstep: {e}", pkg.display()));
    let parsed: serde_json::Value =
        serde_json::from_str(&raw).expect("repo package.json parses as JSON");
    let version = parsed["version"]
        .as_str()
        .expect("repo package.json has a string version field");
    println!("cargo:rustc-env=ORCHESTRA_APP_VERSION={version}");

    // ---- 2. chime WAVs → OUT_DIR/chime_assets.rs ----
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let wav_dir = out_dir.join("chimes");
    std::fs::create_dir_all(&wav_dir).expect("create chime OUT_DIR");

    let mut table = String::new();
    table.push_str(
        "/// Generated by build.rs — every chime recipe rendered to WAV.\n\
         pub const CHIMES: &[ChimeAsset] = &[\n",
    );
    for recipe in chime_gen::recipes() {
        let wav_ref = if recipe.id == "none" {
            "&[]".to_string()
        } else {
            let wav = chime_gen::render_wav(&recipe);
            let path = wav_dir.join(format!("{}.wav", recipe.id));
            std::fs::write(&path, wav).expect("write chime wav");
            format!(
                "include_bytes!(concat!(env!(\"OUT_DIR\"), \"/chimes/{}.wav\"))",
                recipe.id
            )
        };
        writeln!(
            table,
            "    ChimeAsset {{ id: {:?}, name: {:?}, description: {:?}, wav: {} }},",
            recipe.id, recipe.name, recipe.description, wav_ref
        )
        .unwrap();
    }
    table.push_str("];\n");
    std::fs::write(out_dir.join("chime_assets.rs"), table).expect("write chime_assets.rs");
    // The recipes live in chime-gen's source; cargo already rebuilds when a
    // build-dependency changes, so no extra rerun-if-changed is needed.

    // ---- 3. icons/*.svg → OUT_DIR/icons.gresource ----
    // The Electron side hand-writes 39 inline SVGs (src/renderer/**/*.tsx) and
    // recolours them via `fill="currentColor"`. GTK's equivalent is a symbolic
    // icon: a `-symbolic`-suffixed name resolves through the IconTheme and is
    // recoloured to the widget's CSS `color`, which is what keeps a single asset
    // working across hover/active/accent states instead of baking one colour in.
    //
    // The SVGs are compiled into a GResource and embedded in the binary (same
    // reason the chimes above are: the shipped artifact must be self-contained).
    // A filesystem icon search path would be the other option, but it would put
    // the assets outside the binary, so a packaging slip becomes a runtime UI
    // defect instead of a build failure. (A missing icon at run time renders
    // GTK's broken-image placeholder — visible, not silent; measured in
    // src/icons.rs's module docs. Embedding is about not shipping the breakage,
    // not about the breakage being invisible.)
    let icon_dir = Path::new(&manifest).join("icons");
    println!("cargo:rerun-if-changed={}", icon_dir.display());
    let mut icons: Vec<String> = std::fs::read_dir(&icon_dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", icon_dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| n.ends_with(".svg"))
        .collect();
    icons.sort();
    assert!(!icons.is_empty(), "icons/ contains no .svg assets");

    // GTK looks icons up under <resource-path>/icons/<theme>/<size>/<name>.svg;
    // `scalable/actions` is the standard location for symbolic assets.
    let mut xml = String::from("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<gresources>\n");
    writeln!(
        xml,
        "  <gresource prefix=\"/dev/orchestra/gtk/icons/scalable/actions\">"
    )
    .unwrap();
    for name in &icons {
        writeln!(xml, "    <file preprocess=\"xml-stripblanks\">{name}</file>").unwrap();
    }
    xml.push_str("  </gresource>\n</gresources>\n");
    let xml_path = out_dir.join("icons.gresource.xml");
    std::fs::write(&xml_path, xml).expect("write icons.gresource.xml");

    // `glib-compile-resources` ships in glib2-devel, which CI installs
    // system-wide. The rootless dev setup (native/setup-localdeps.sh) extracts
    // it into .localdeps/prefix instead and env.sh does not put that on PATH,
    // so fall back to querying pkg-config for glib's own tool directory rather
    // than requiring every developer to extend PATH by hand.
    let gresource = out_dir.join("icons.gresource");
    let compiler = std::env::var("GLIB_COMPILE_RESOURCES")
        .ok()
        .filter(|p| !p.is_empty())
        .or_else(|| {
            // Ask pkg-config where glib keeps the tool. NOTE: on the rootless
            // setup this answers `/usr/bin/glib-compile-resources` — the path
            // the extracted RPM *would* install to — while the binary actually
            // lives under the localdeps prefix, so the answer is checked with
            // is_file() and both candidates are tried. Trusting the variable
            // blindly is what made the first attempt at this fail.
            let var = |name: &str| -> Option<String> {
                let out = std::process::Command::new("pkg-config")
                    .args([&format!("--variable={name}"), "gio-2.0"])
                    .output()
                    .ok()?;
                Some(String::from_utf8(out.stdout).ok()?.trim().to_string())
                    .filter(|s| !s.is_empty())
            };
            let direct = var("glib_compile_resources");
            // Both `glib_compile_resources` and `prefix` report /usr even under
            // the rootless setup — the extracted .pc files describe where the
            // RPM *would* install, not where it was unpacked. The only thing
            // that actually knows the real root is PKG_CONFIG_PATH, so walk up
            // from each entry (…/prefix/usr/lib64/pkgconfig → …/prefix/usr) and
            // look for bin/ there.
            let from_pc_path = std::env::var("PKG_CONFIG_PATH")
                .unwrap_or_default()
                .split(':')
                .filter(|s| !s.is_empty())
                .filter_map(|entry| {
                    let root = Path::new(entry).parent()?.parent()?;
                    Some(root.join("bin/glib-compile-resources"))
                })
                .find(|p| p.is_file())
                .map(|p| p.to_string_lossy().into_owned());

            [direct, from_pc_path]
                .into_iter()
                .flatten()
                .find(|p| Path::new(p).is_file())
        })
        .unwrap_or_else(|| "glib-compile-resources".to_string());

    let status = std::process::Command::new(&compiler)
        .arg("--sourcedir")
        .arg(&icon_dir)
        .arg("--target")
        .arg(&gresource)
        .arg(&xml_path)
        .status()
        .unwrap_or_else(|e| {
            panic!(
                "cannot run {compiler}: {e}\n\
                 glib-compile-resources comes from glib2-devel. If it is installed \
                 outside PATH (the rootless .localdeps prefix), set \
                 GLIB_COMPILE_RESOURCES to its full path."
            )
        });
    assert!(status.success(), "{compiler} failed on {}", xml_path.display());
    // Fail the build rather than let an empty/missing bundle ship: an icon that
    // doesn't resolve draws nothing at run time, with no error to notice.
    let compiled = std::fs::metadata(&gresource).expect("icons.gresource was produced");
    assert!(compiled.len() > 0, "icons.gresource is empty");

    // ---- 4. link libfontconfig by exact soname ----
    // `-l:libfontconfig.so.1` rather than `-lfontconfig`: the rootless localdeps
    // prefix has no `-devel` `libfontconfig.so` symlink, so the plain `-l` form
    // can't resolve. The soname is ABI-stable.
    println!("cargo:rustc-link-arg=-l:libfontconfig.so.1");
}
