// Render the chime recipes (native/chime-gen — the port of
// src/renderer/chime.ts) into OUT_DIR at build time. sound.rs embeds the
// bytes via the generated chime_assets.rs, so the app binary is
// self-contained and the shipped audio can never drift from the recipe
// tables (chime-gen's tests pin those against chime.ts).

use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let wav_dir = out_dir.join("chimes");
    std::fs::create_dir_all(&wav_dir).expect("create chime OUT_DIR");

    let mut table = String::new();
    table.push_str(
        "/// Generated by build.rs — every chime recipe rendered to WAV.\n\
         pub const CHIMES: &[ChimeAsset] = &[\n",
    );
    for recipe in chime_gen::recipes() {
        let wav_ref = if recipe.id == "none" {
            "&[]".to_string()
        } else {
            let wav = chime_gen::render_wav(&recipe);
            let path = wav_dir.join(format!("{}.wav", recipe.id));
            std::fs::write(&path, wav).expect("write chime wav");
            format!("include_bytes!(concat!(env!(\"OUT_DIR\"), \"/chimes/{}.wav\"))", recipe.id)
        };
        writeln!(
            table,
            "    ChimeAsset {{ id: {:?}, name: {:?}, description: {:?}, wav: {} }},",
            recipe.id, recipe.name, recipe.description, wav_ref
        )
        .unwrap();
    }
    table.push_str("];\n");
    std::fs::write(out_dir.join("chime_assets.rs"), table).expect("write chime_assets.rs");

    // The recipes live in chime-gen's source; cargo already rebuilds when a
    // build-dependency changes, so no extra rerun-if-changed is needed.
}
